version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:4.0

volumes:
  bundle:
    driver: local
